require File.expand_path("..", __FILE__)+'/entities/library'

lib = Library.new

lib.author_add("Lev Tolstoy")
lib.author_add("Gustave Flaubert")
lib.author_add("Mark Twain")
lib.author_add("George Eliot")
lib.author_add("Herman Melville")
lib.author_add("Charles Dickens")
lib.author_add("Fedor Dostoevsky")
lib.author_add("Jane Austen")

lib.book_add("War and Peace", lib.author("Lev Tolstoy"))
lib.book_add("Anna Karenina", lib.author("Lev Tolstoy"))
lib.book_add("Madame Bovary", lib.author("Gustave Flaubert"))
lib.book_add("The Adventures of Huckleberry Finn", lib.author("Mark Twain"))
lib.book_add("Middlemarch", lib.author("George Eliot"))
lib.book_add("Moby Dick", lib.author("Herman Melville"))
lib.book_add("Great expectations", lib.author("Charles Dickens"))
lib.book_add("Crime and Punishment", lib.author("Fedor Dostoevsky"))
lib.book_add("Emma", lib.author("Jane Austen"))

lib.reader_add("Lena","l@gmail.com","Dnepr","St. Polya",5)
lib.reader_add("Den","d@gmail.com","Dnepr","St. Korolenko",15)
lib.reader_add("Kira","k@gmail.com","Dnepr","St. Havana",20)
lib.reader_add("Marta","m@gmail.com","Dnepr","St. Glinka",7)
lib.reader_add("Max","mm@gmail.com","Dnepr","St. Glinka",18)
lib.reader_add("Ron","r@gmail.com","Dnepr","St. Glinka",44)
lib.reader_add("Alf","a@gmail.com","Dnepr","St. Zalivnaya",88)
lib.reader_add("Ivan","i@gmail.com","Dnepr","St. Zalivnaya",9)
lib.reader_add("Dina","dd@gmail.com","Dnepr","St. Korolenko",22)

lib.order_db_clear

lib.order_save(Order.new(lib.book("War and Peace"), lib.reader("Lena"), Time.local(2017,1,1,20,15,1)))
lib.order_save(Order.new(lib.book("War and Peace"), lib.reader("Alf"), Time.local(2017,1,5,20,15,1)))
lib.order_save(Order.new(lib.book("Anna Karenina"), lib.reader("Den"), Time.local(2017,1,5,20,15,1)))
lib.order_save(Order.new(lib.book("Anna Karenina"), lib.reader("Kira"), Time.local(2017,1,10,20,15,1)))
lib.order_save(Order.new(lib.book("Anna Karenina"), lib.reader("Marta"), Time.local(2017,1,11,20,15,1)))
lib.order_save(Order.new(lib.book("Madame Bovary"), lib.reader("Alf"), Time.local(2017,2,1,20,15,1)))
lib.order_save(Order.new(lib.book("The Adventures of Huckleberry Finn"), lib.reader("Dina"), Time.local(2017,2,1,20,15,1)))
lib.order_save(Order.new(lib.book("Middlemarch"), lib.reader("Ivan"), Time.local(2017,3,2,20,15,1)))
lib.order_save(Order.new(lib.book("Moby Dick"), lib.reader("Den"), Time.local(2017,3,5,20,15,1)))
lib.order_save(Order.new(lib.book("Moby Dick"), lib.reader("Kira"), Time.local(2017,3,10,20,15,1)))
lib.order_save(Order.new(lib.book("Moby Dick"), lib.reader("Marta"), Time.local(2017,4,10,20,15,1)))
lib.order_save(Order.new(lib.book("Moby Dick"), lib.reader("Max"), Time.local(2017,4,10,20,15,1)))
lib.order_save(Order.new(lib.book("Moby Dick"), lib.reader("Ron"), Time.local(2017,5,12,20,15,1)))
lib.order_save(Order.new(lib.book("Great expectations"), lib.reader("Dina"), Time.local(2017,5,20,20,15,1)))
lib.order_save(Order.new(lib.book("Great expectations"), lib.reader("Lena"), Time.local(2017,6,3,20,15,1)))
lib.order_save(Order.new(lib.book("Crime and Punishment"), lib.reader("Alf"), Time.local(2017,6,5,20,15,1)))
lib.order_save(Order.new(lib.book("Moby Dick"), lib.reader("Alf"), Time.local(2017,6,6,20,15,1)))
lib.order_save(Order.new(lib.book("Crime and Punishment"), lib.reader("Ron"), Time.local(2017,7,4,20,15,1)))
lib.order_save(Order.new(lib.book("Crime and Punishment"), lib.reader("Ivan"), Time.local(2017,7,12,20,15,1)))
lib.order_save(Order.new(lib.book("Emma"), lib.reader("Dina"), Time.local(2017,8,9,20,15,1)))
lib.order_save(Order.new(lib.book("Emma"), lib.reader("Alf"), Time.local(2017,9,11,20,15,1)))
